"""add cover_path to track

Revision ID: 2d2e48cf1619
Revises: 1e9fa0917b8f
Create Date: 2025-06-07 19:05:23.500285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2e48cf1619'
down_revision = '1e9fa0917b8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('cover_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'cover_path')
    # ### end Alembic commands ### 