"""add_albums_playlists_likes

Revision ID: 381592141436
Revises: 2d2e48cf1619
Create Date: 2025-06-07 19:11:08.113549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381592141436'
down_revision = '2d2e48cf1619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('album_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tracks_artist'), 'tracks', ['artist'], unique=False)
    op.create_index(op.f('ix_tracks_id'), 'tracks', ['id'], unique=False)
    op.create_index(op.f('ix_tracks_title'), 'tracks', ['title'], unique=False)
    op.create_foreign_key(None, 'tracks', 'albums', ['album_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_index(op.f('ix_tracks_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_artist'), table_name='tracks')
    op.drop_column('tracks', 'album_id')
    # ### end Alembic commands ### 